parkjongco/dnz_react

src/App.js
src/components/pages/Login/StoreDetail/ReserveButton/ReserveButton.jsx
src/components/pages/Login/StoreDetail/ReserveButton/ReserveButton.module.css
src/components/pages/Login/StoreDetail/ReserveButton/ReserveModal/ReserveModal.jsx
src/components/pages/Login/StoreDetail/ReserveButton/ReserveModal/ReserveModal.module.css
src/components/pages/Login/StoreDetail/StoreDetail.jsx

예약 모달 스타일 작업

---

src/App.js

import 경로 재설정

---

src/App.js
src/components/pages/Login/Index.jsx
src/components/pages/MyDining/MyDining.jsx
src/components/pages/MyDining/MyDining.module.css
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ConfirmReserveModal/ConfirmReserveModal.jsx

나의 예약 페이지 생성

---

src/components/Header/Header.css
src/components/Header/Header.jsx
src/components/pages/Alampage/Alam.css
src/components/pages/Alampage/Alam.jsx

알람 페이지 및 헤더 실시간 알림 기능

---

src/components/pages/StoreDetail/ReserveButton/ReserveButton.jsx
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ConfirmReserveModal/ConfirmReserveButton/FinalConfirmReserveModal/FinalConfirmReserveModal.jsx
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ConfirmReserveModal/ConfirmReserveModal.jsx
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ReserveModal.jsx

예약 페이지 음식점 seq 정보 추가

---

src/components/pages/StoreDetail/StoreDetail.css
src/components/pages/StoreDetail/StoreDetail.jsx

detail fix

---

src/components/pages/StoreDetail/ReserveButton/ReserveButton.jsx
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ConfirmReserveModal/ConfirmReserveButton/ConfirmReseveButton.jsx
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ConfirmReserveModal/ConfirmReserveButton/FinalConfirmReserveModal/FinalConfirmReserveButton/FinalConfirmReserveButton.jsx
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ConfirmReserveModal/ConfirmReserveButton/FinalConfirmReserveModal/FinalConfirmReserveModal.jsx
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ConfirmReserveModal/ConfirmReserveModal.jsx
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ReserveModal.jsx

예약 음식점 이름 출력 및 날짜 형식 변경

---

src/components/Header/Header.css
src/components/Header/Header.jsx
src/components/pages/Alampage/Alam.css
src/components/pages/Alampage/Alam.jsx
src/components/pages/Login/LoginForm/Login.jsx
src/components/store/store.js

1차적 알람 기능 완료

---

src/components/Header/Header.jsx
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ConfirmReserveModal/ConfirmReserveButton/FinalConfirmReserveModal/FinalConfirmReserveButton/FinalConfirmReserveButton.jsx
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ConfirmReserveModal/ConfirmReserveButton/FinalConfirmReserveModal/FinalConfirmReserveButton/ReserveDetail/ReserveDetail.jsx
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ConfirmReserveModal/ConfirmReserveButton/FinalConfirmReserveModal/FinalConfirmReserveButton/ReserveDetail/ReserveDetail.module.css
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ConfirmReserveModal/ConfirmReserveButton/FinalConfirmReserveModal/FinalConfirmReserveModal.jsx
src/components/pages/StoreDetail/StoreDetail.jsx

사용자 예약 페이지 조회 기능 추가

---

src/components/Header/Header.jsx
src/components/pages/StoreAddPage/StoreAddPage.jsx
src/components/pages/StoreAddPage/StoreAddPage.module.css
src/components/pages/StoreManagementPage/StoreManagementPage.jsx

가게관리 출력 개선

---

src/components/pages/StoreDetail/ReserveButton/ReserveModal/ConfirmReserveModal/ConfirmReserveButton/FinalConfirmReserveModal/FinalConfirmReserveButton/ReserveDetail/ReserveDetail.jsx
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ConfirmReserveModal/ConfirmReserveButton/FinalConfirmReserveModal/FinalConfirmReserveModal.jsx

예약 조회 디자인 변경

---

src/components/pages/MyDining/MyDining.jsx
src/components/pages/MyDining/MyDining.module.css
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ConfirmReserveModal/ConfirmReserveButton/FinalConfirmReserveModal/FinalConfirmReserveButton/ReserveDetail/ReserveDetail.jsx
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ReserveModal.jsx
src/components/pages/StoreDetail/ReserveButton/ReserveModal/ReserveModal.module.css

예약 등록시 현재 시간 이후 시간 버튼만 생성, 캘린더 오늘 날짜 이전 선택 제어, 예약 확인 페이지 현재 시간 이후 리뷰 작성 버튼으로 변경, 당일 날짜 예약 취소 시 confirm으로 3일간 예약 금지 띄움

예약 확인 페이지 및 예약 등록 제어 기능 추가

---

src/App.js
src/components/Body/PopularRestaurants/PopularRestaurants.jsx
src/components/Header/Header.css
src/components/Header/Header.jsx
src/pages/StoreDetail/StoreDetail.css
src/pages/StoreDetail/StoreDetail.jsx
src/pages/StoreList/StoreList.jsx
src/pages/StoreList/StoreList.module.css

헤더 부분에 로그인이 유저아이콘 추가 했고 유저아이콘 클릭시 마이페이지로 넘어가게 추가 
해당 가게 카테고리들 항목에 더보기 버튼을 눌렀을때 storelist에 해당 카테고리에 맞게 가게들 리스트 출력

mypage and store list 추가

---

src/pages/MyDining/MyDining.jsx
src/pages/MyDining/ReviewDetail/ReviewDetail.jsx
src/pages/StoreDetail/ReserveButton/ReserveModal/ReserveModal.jsx

리뷰 버튼 생성 시점 변경 및 리뷰 답글 공간 생성

---

package-lock.json
src/pages/Alampage/Alam.css
src/pages/Alampage/Alam.jsx
src/utils/store.js

알람 핸들러 수정 및 스토어 수정

---

src/pages/MyDining/MyDining.jsx

리뷰 상태 불러오기 부분 수정

---

src/pages/MyDining/MyDining.jsx
src/pages/MyDining/MyDining.module.css
src/pages/MyDining/ReviewDetailModal/ReviewDetaiModall.jsx
src/pages/MyDining/ReviewModal/ReviewModal.jsx

리뷰 제출 후 상태 업데이트 및 리뷰 답글 불러오기

---

src/pages/MyDining/MyDining.jsx

제한 주기 위해 취소 시간 저장

---

src/pages/StoreDetail/StoreDetail.css
src/pages/StoreDetail/StoreDetail.jsx

가게 상세 페이지에서 리뷰 출력 추가

---

src/pages/StoreDetail/ReserveButton/ReserveModal/ReserveModal.jsx
src/pages/StoreDetail/ReserveButton/ReserveModal/ReserveModal.module.css
src/pages/StoreDetail/StoreDetail.jsx

남은 좌석수에 따른 예약 등록 제한 및
좌석 수 관리 기능 개선
예약 등록 기능의 오동작 제어 및 개선

예약 등록 코드 개선

---

src/pages/MyDining/MyDining.jsx
src/pages/MyDining/MyDining.module.css
src/pages/Mypages/Mypage.jsx
src/pages/StoreDetail/ReserveButton/ReserveModal/ReserveModal.jsx
src/pages/StoreDetail/ReserveButton/ReserveModal/ReserveModal.module.css
src/pages/StoreDetail/StoreDetail.css

예약 내역 가게 이미지 없을 경우 default 이미지 및 마이페이지에서 예약 내역 추가

예약 내역 가게 이미지 없을 경우 default 이미지 및 마이페이지에서 예약 내역 추가
